### ISSUE TITLE
Use it in GitHub Actions

### ISSUE THREAD

**Issue by cristianat98** [lietu/go-pre-commit#6]
Hi,

I was trying to use the go-pre-commit library for the GitHub Actions with the following configuration:
```
  - repo: https://github.com/lietu/go-pre-commit
    rev: v0.1.0
    hooks:
    - id: gofumpt
    - id: golangci-lint
    - id: go-mod-tidy
```

It gives me some errors in the golangci-lint:
golangci-lint............................................................Failed
- hook id: golangci-lint
- exit code: 1

Error: parallel golangci-lint is running
Failed executing command with error: parallel golangci-lint is running
Error running golangci-lint: exit status 3

I was trying to add the arg --allow-parallel-runners but it doesn't work in the go-pre-commit. Is there a way to make it work with the github actions workflow ?
